[project]
name = "django-snomed-ct"
description = "A Django App for storing, managing, and querying SNOMED CT by itself or as part of a Django application."
version = "0.5.2"
readme = "README.md"

license = {file = "LICENSE"}
keywords = []
authors = [
  { name = "Chimezie Ogbuji", email = "chimezie@gmail.com" }
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "django>=5.2",
]

[project.optional-dependencies]
vector-db = [
  "en-core-sci-lg @ https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_core_sci_lg-0.5.4.tar.gz",
  "sentence_transformers",
  "numpy<2.0",
  "spacy==3.7.5",
  "scispacy==0.6.2",
  "ogbujipt",
]

[build-system]
requires = ["setuptools >= 61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu" },
]
torchvision = [
    { index = "pytorch-cpu" },
]
torchaudio = [
    { index = "pytorch-cpu" },
]
